### ISSUE TITLE
ViewHabitEvent: returning from AddHabitEvent crash on selecting new HabitEvent

### ISSUE THREAD

**Issue by gojeffcho** [CMPUT301F17T29/HabitUp#111]
Repro steps:
1. Go to ViewHabitEvent
2. Add a new HabitEvent
3. On return to ViewHabitEvent, select the new HabitEvent that was just created
4. Select View or Edit
5. ES does not grab the HabitEvent (gets null - see HabitEventDEBUG in log output) and causes a crash.

Reproducibility: 100%

Severity: HIGH

**Comment by sharibarboza** [comment]
Is this an ES issue or an Activity issue? Right now I am currently trying to optimize our ViewHabitEventActivity so I can take this one.

**Comment by gojeffcho** [comment]
@sharibarboza I haven't done any bugfinding on it yet - I think it may be an ES issue, again with the synchronicity.  I'm not sure _why_, though, because the AddHabitEvent task was also updated to be refresh-forced, so in theory the pipeline should be clearing.  I think it might be something to do with the adaptor as well, since it's returning NULL for the selection value.  Let me try something real fast, I'll get it to print out the object it's selecting when clicking...

**Comment by sharibarboza** [comment]
I am currently trying to utilize recyclerview which uses a new more optimized adapter. So maybe still figure out what the adapter is doing just in case but I am going to be changing this anyways if it works later on.

**Comment by gojeffcho** [comment]
OK... it just went from 100% repro to 0% repro without me doing anything.

Could've been ES fuckery?

**Comment by gojeffcho** [comment]
Reassigned priority to Medium as repro went down, at least for me.
