### ISSUE TITLE
Add method for computing habit progression status

### ISSUE THREAD

**Issue by sharibarboza** [CMPUT301F17T29/HabitUp#15]
There should be some method in the Habit model to calculate the habit status from the user story: [US 01.08.01](https://github.com/CMPUT301F17T29/HabitUp/wiki/User-Stories).

> As a participant, I want for each habit type, a visual and statistical habit status indicator to show how closely I am following its plan.

There needs to be an x value and a y value, where x is the number of habit events that the user has actually completed for that habit, and y is the number of total habit events that the user *should* have completed since the habit's start date. The methods should be able to set and provide access to these x and y variables.

**Comment by gojeffcho** [comment]
Shared the demo of this in Slack.  Will be implementing shortly.
