### ISSUE TITLE
EditHabit: App back works, but system back crashes

### ISSUE THREAD

**Issue by gojeffcho** [CMPUT301F17T29/HabitUp#84]
From EditHabit in view mode, both the app back (arrow on the top left) and system soft back (left triangle at the bottom) work properly.  However, from EditHabit in edit mode, the app back button seems to work, but the system soft back causes an app crash.  This is 100% repro behavior.  No troubleshooting done from my end.

**Comment by sharibarboza** [comment]
Looks like I have to Override the onBackPressed() when returning to the ViewHabitActivity. I'll do this later as I'm still on other things right now.
